# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 12
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 12
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_util.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 100
  Exclude:

Metrics/ParameterLists:
  Max: 5

Lint/SpaceBeforeFirstArg:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/FirstParameterIndentation:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IndentHash:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/RescueModifier:
  Enabled: true
