#!/usr/bin/env ruby

require_relative 'lib/sawaal/color'
require_relative 'lib/sawaal/tty'
require_relative 'lib/sawaal/selector'

puts 'starting'
puts Sawaal::Selector.choose(
    'which key is the best?', {
      :key1 => 'key1 is the best',
      :key2 => 'key2 is the best for sure',
      :key3 => 'key3 might be the one',
      :key4 => 'key4 is surely the best',
      :key5 => 'key5'
    })
